<?php

class sugoi_form_elements_FakeFlag extends Enum {
	public static $Flag1;
	public static $Flag10;
	public static $Flag11;
	public static $Flag12;
	public static $Flag13;
	public static $Flag14;
	public static $Flag15;
	public static $Flag16;
	public static $Flag17;
	public static $Flag18;
	public static $Flag19;
	public static $Flag2;
	public static $Flag20;
	public static $Flag21;
	public static $Flag22;
	public static $Flag23;
	public static $Flag24;
	public static $Flag25;
	public static $Flag26;
	public static $Flag27;
	public static $Flag28;
	public static $Flag29;
	public static $Flag3;
	public static $Flag30;
	public static $Flag31;
	public static $Flag32;
	public static $Flag4;
	public static $Flag5;
	public static $Flag6;
	public static $Flag7;
	public static $Flag8;
	public static $Flag9;
	public static $__constructors = array(0 => 'Flag1', 9 => 'Flag10', 10 => 'Flag11', 11 => 'Flag12', 12 => 'Flag13', 13 => 'Flag14', 14 => 'Flag15', 15 => 'Flag16', 16 => 'Flag17', 17 => 'Flag18', 18 => 'Flag19', 1 => 'Flag2', 19 => 'Flag20', 20 => 'Flag21', 21 => 'Flag22', 22 => 'Flag23', 23 => 'Flag24', 24 => 'Flag25', 25 => 'Flag26', 26 => 'Flag27', 27 => 'Flag28', 28 => 'Flag29', 2 => 'Flag3', 29 => 'Flag30', 30 => 'Flag31', 31 => 'Flag32', 3 => 'Flag4', 4 => 'Flag5', 5 => 'Flag6', 6 => 'Flag7', 7 => 'Flag8', 8 => 'Flag9');
	}
sugoi_form_elements_FakeFlag::$Flag1 = new sugoi_form_elements_FakeFlag("Flag1", 0);
sugoi_form_elements_FakeFlag::$Flag10 = new sugoi_form_elements_FakeFlag("Flag10", 9);
sugoi_form_elements_FakeFlag::$Flag11 = new sugoi_form_elements_FakeFlag("Flag11", 10);
sugoi_form_elements_FakeFlag::$Flag12 = new sugoi_form_elements_FakeFlag("Flag12", 11);
sugoi_form_elements_FakeFlag::$Flag13 = new sugoi_form_elements_FakeFlag("Flag13", 12);
sugoi_form_elements_FakeFlag::$Flag14 = new sugoi_form_elements_FakeFlag("Flag14", 13);
sugoi_form_elements_FakeFlag::$Flag15 = new sugoi_form_elements_FakeFlag("Flag15", 14);
sugoi_form_elements_FakeFlag::$Flag16 = new sugoi_form_elements_FakeFlag("Flag16", 15);
sugoi_form_elements_FakeFlag::$Flag17 = new sugoi_form_elements_FakeFlag("Flag17", 16);
sugoi_form_elements_FakeFlag::$Flag18 = new sugoi_form_elements_FakeFlag("Flag18", 17);
sugoi_form_elements_FakeFlag::$Flag19 = new sugoi_form_elements_FakeFlag("Flag19", 18);
sugoi_form_elements_FakeFlag::$Flag2 = new sugoi_form_elements_FakeFlag("Flag2", 1);
sugoi_form_elements_FakeFlag::$Flag20 = new sugoi_form_elements_FakeFlag("Flag20", 19);
sugoi_form_elements_FakeFlag::$Flag21 = new sugoi_form_elements_FakeFlag("Flag21", 20);
sugoi_form_elements_FakeFlag::$Flag22 = new sugoi_form_elements_FakeFlag("Flag22", 21);
sugoi_form_elements_FakeFlag::$Flag23 = new sugoi_form_elements_FakeFlag("Flag23", 22);
sugoi_form_elements_FakeFlag::$Flag24 = new sugoi_form_elements_FakeFlag("Flag24", 23);
sugoi_form_elements_FakeFlag::$Flag25 = new sugoi_form_elements_FakeFlag("Flag25", 24);
sugoi_form_elements_FakeFlag::$Flag26 = new sugoi_form_elements_FakeFlag("Flag26", 25);
sugoi_form_elements_FakeFlag::$Flag27 = new sugoi_form_elements_FakeFlag("Flag27", 26);
sugoi_form_elements_FakeFlag::$Flag28 = new sugoi_form_elements_FakeFlag("Flag28", 27);
sugoi_form_elements_FakeFlag::$Flag29 = new sugoi_form_elements_FakeFlag("Flag29", 28);
sugoi_form_elements_FakeFlag::$Flag3 = new sugoi_form_elements_FakeFlag("Flag3", 2);
sugoi_form_elements_FakeFlag::$Flag30 = new sugoi_form_elements_FakeFlag("Flag30", 29);
sugoi_form_elements_FakeFlag::$Flag31 = new sugoi_form_elements_FakeFlag("Flag31", 30);
sugoi_form_elements_FakeFlag::$Flag32 = new sugoi_form_elements_FakeFlag("Flag32", 31);
sugoi_form_elements_FakeFlag::$Flag4 = new sugoi_form_elements_FakeFlag("Flag4", 3);
sugoi_form_elements_FakeFlag::$Flag5 = new sugoi_form_elements_FakeFlag("Flag5", 4);
sugoi_form_elements_FakeFlag::$Flag6 = new sugoi_form_elements_FakeFlag("Flag6", 5);
sugoi_form_elements_FakeFlag::$Flag7 = new sugoi_form_elements_FakeFlag("Flag7", 6);
sugoi_form_elements_FakeFlag::$Flag8 = new sugoi_form_elements_FakeFlag("Flag8", 7);
sugoi_form_elements_FakeFlag::$Flag9 = new sugoi_form_elements_FakeFlag("Flag9", 8);
